### PR TITLE
Handle clang PCHs (#539)

### PR DESCRIPTION
**Pull request by ahasselbring**
Closes: #539

### CODE REVIEW

**Comment by ahasselbring** [comment]
Thanks for your comments. While writing tests, I found out that things are a bit more complicated:

1. If the call (similar to the one [CMake uses for PCH generation](https://gitlab.kitware.com/cmake/cmake/-/blob/master/Modules/Compiler/Clang.cmake#L105))
```
ccache clang -Xclang -emit-pch -Xclang -include -Xclang pch.h -o pch.h.pch -c empty.c
```
is executed twice, the second call of ccache will find (through [lines 109-115 of `argprocessing.cpp`](https://github.com/ccache/ccache/blob/master/src/argprocessing.cpp#L109) that `pch.h.pch` exists, and therefore assume that it is included as PCH.
This in turn means that ccache will always refuse to use a cached version of the PCH (besides possible other reasons) because the spuriously included file `pch.h.pch` is newer than the cached one (in fact, they should have the same timestamp as `pch.h.pch` was written and then cached immediately after). clang, however, doesn't actually use `pch.h.pch` so it would be safe for ccache to ignore it. I am not yet sure how clang knows that it can/should ignore the precompiled version of `pch.h`, so I am not sure how ccache can find this out.

2. The preprocessor command that ccache makes out of the above command line looks like
```
ccache clang -Xclang -emit-pch -Xclang -include -Xclang pch.h (-fpch-preprocess if pch.h.pch already exists) -E empty.c
```
which still outputs the binary PCH (obviously due to the `-emit-pch` option) and not just the preprocessed source. As far as I understand, ccache derives the files that a call depends on (and therefore when a cached result is out of date) from the output of the preprocessor. Does this mean that ccache will not be able to find out which headers are included (and thus will not know when it needs to call the compiler)?

I derive the following tasks:
1. Find out how ccache can determine that `clang -Xclang -emit-pch -Xclang -include -Xclang pch.h -o pch.h.pch -c empty.c` does not include `pch.h.pch` if that already exists (which means finding out what clang does in this case - maybe it's just the `-emit-pch` option that tells clang not to look for included PCHs, but since clang has chained PCHs, that seems not correct).
2. Eliminate `-Xclang -emit-pch` from the preprocessor call (by making `-emit-pch` a compiler only arg? what about `-emit-pth`? Do `-emit-pch` and `-emit-pth` even exist as anything else than clang-cc1 arguments?), thereby making the preprocessor output look normal and enabling ccache to derive included files properly.
Do you agree with this?

**Comment by jrosdahl** [comment]
> 1. The preprocessor command that ccache makes out of the above command line looks like
> 
> ```
> ccache clang -Xclang -emit-pch -Xclang -include -Xclang pch.h (-fpch-preprocess if pch.h.pch already exists) -E empty.c
> ```
> 
> which still outputs the binary PCH (obviously due to the `-emit-pch` option) and not just the preprocessed source. As far as I understand, ccache derives the files that a call depends on (and therefore when a cached result is out of date) from the output of the preprocessor. Does this mean that ccache will not be able to find out which headers are included (and thus will not know when it needs to call the compiler)?

ccache uses the preprocessed output for two things:

1. Computing (along with other information) a hash that uniquely identifies the result.
2. Remembering which header files were read when compiling. This information is used for future potential ["direct mode"](https://ccache.dev/manual/3.7.10.html#_the_direct_mode) hits. 

For this phase ccache shouldn't have to know the output file (the emitted pch file), so excluding `-emit-pch` from the preprocessor command sounds good. (Not sure if I understood your question so maybe this wasn't the answer you sought?)

> I derive the following tasks:
> 
> 1. Find out how ccache can determine that `clang -Xclang -emit-pch -Xclang -include -Xclang pch.h -o pch.h.pch -c empty.c` does not include `pch.h.pch` if that already exists (which means finding out what clang does in this case - ~maybe it's just the `-emit-pch` option that tells clang not to look for included PCHs, but since clang has chained PCHs, that seems not correct~ apparently, the cc1 option `-include` (in contrast to the frontend option `-include`) never looks for PCHs, so that's an easy fix).

OK.

> 2. Eliminate `-Xclang -emit-pch` from the preprocessor call (by making `-emit-pch` a compiler only arg? what about `-emit-pth`? Do `-emit-pch` and `-emit-pth` even exist as anything else than clang-cc1 arguments?),

No idea. I always have to look up stuff related to PCHs since I don't use them myselves.

> thereby making the preprocessor output look normal and enabling ccache to derive included files properly.
>    Do you agree with this?

Yes.

**Comment by ahasselbring** [comment]
The last commits already integrated the proposed changes, and as far as I can tell everything works as expected now.

**Comment by jrosdahl** [comment]
Thanks.

**Pull request merged**
