### PR TITLE
Travis: use wine for mingw unittest

### PR DESCRIPTION
**Pull request by afbjorklund**
Investigate if it would be possible to run the `unittest/run.exe`, using [Wine](https://www.winehq.org/) ?

Goes in after #246 (for Cygwin), most likely there could some additional issues.

### CODE REVIEW

**Comment by afbjorklund** [comment]
Typical, the binfmt support in Travis is broken: https://github.com/travis-ci/travis-ci/issues/4171

`unittest/run.exe: 1: unittest/run.exe: MZ����@���: not found`

Might need to have to invent some kind of wrapper syntax

Perhaps some kind of prefix variable in Make, for the run:

``` make
.PHONY: unittest
unittest: unittest/run$(EXEEXT)
        $(WINE) unittest/run$(EXEEXT)


```

**Comment by afbjorklund** [comment]
Getting some issues locally as well:
```
unittest/run.exe
fixme:volume:GetVolumePathNameA ("Z:\\home\\anders\\ccache\\testdir.8\\argument_processing\\sysroot_should_be_rewritten_if_basedir_is_used", 0x6ffc4c, 4), stub!
fixme:volume:GetVolumePathNameW (L"Z:\\home\\anders\\ccache\\testdir.8\\argument_processing\\sysroot_should_be_rewritten_if_basedir_is_used", 0x140ca8, 4), stub!
fixme:volume:GetVolumePathNameA ("Z:\\home\\anders\\ccache\\testdir.8\\argument_processing\\sysroot_with_separate_argument_should_be_rewritten_if_basedir_is_used", 0x6ffc4c, 4), stub!
fixme:volume:GetVolumePathNameW (L"Z:\\home\\anders\\ccache\\testdir.8\\argument_processing\\sysroot_with_separate_argument_should_be_rewritten_if_basedir_is_used", 0x140ca8, 4), stub!
fixme:volume:GetVolumePathNameA ("Z:\\home\\anders\\ccache\\testdir.8\\argument_processing\\isystem_flag_with_separate_arg_should_be_rewritten_if_basedir_is_used", 0x6ffc4c, 4), stub!
fixme:volume:GetVolumePathNameW (L"Z:\\home\\anders\\ccache\\testdir.8\\argument_processing\\isystem_flag_with_separate_arg_should_be_rewritten_if_basedir_is_used", 0x140ca8, 4), stub!
unittest/test_conf.c:346: Failed assertion:
  Suite:      conf
  Test:       conf_set_new_value
  Expression: conf_set_value_in_file("ccache.conf", "stats", "chocolate", &errmsg)
  Message:    rename ccache.conf.tmp.anders-ThinkPad.8.P1kAlM to ccache.conf: No such file or directory

unittest/test_conf.c:359: Failed assertion:
  Suite:      conf
  Test:       conf_set_existing_value
  Expression: conf_set_value_in_file("ccache.conf", "path", "vanilla", &errmsg)
  Message:    rename ccache.conf.tmp.anders-ThinkPad.8.iG2Kb7 to ccache.conf: No such file or directory

fixme:msvcrt:MSVCRT__wsopen_s : pmode 0x01b6 ignored
fixme:msvcrt:MSVCRT__wsopen_s : pmode 0x01b6 ignored
fixme:msvcrt:MSVCRT__wsopen_s : pmode 0x01b6 ignored
fixme:msvcrt:MSVCRT__wsopen_s : pmode 0x01b6 ignored
fixme:msvcrt:MSVCRT__wsopen_s : pmode 0x01b6 ignored
fixme:msvcrt:MSVCRT__wsopen_s : pmode 0x01b6 ignored
fixme:msvcrt:MSVCRT__wsopen_s : pmode 0x01b6 ignored
fixme:msvcrt:MSVCRT__wsopen_s : pmode 0x01b6 ignored
fixme:msvcrt:MSVCRT__wsopen_s : pmode 0x01b6 ignored
fixme:msvcrt:MSVCRT__wsopen_s : pmode 0x01b6 ignored
FAILED: 2 tests

```

**Comment by afbjorklund** [comment]
Stupid Wine:

```
wineconsole unittest/run.exe
Application tried to create a window, but no driver could be loaded.
Make sure that your X server is running and that $DISPLAY is set correctly.
err:systray:initialize_systray Could not create tray window
Application tried to create a window, but no driver could be loaded.
Make sure that your X server is running and that $DISPLAY is set correctly.

```

I thought the whole _point_ of using `wineconsole` (over `wine`), was to _not_ create a window...

And that exit code looks a bit wrong, too: <https://travis-ci.org/ccache/ccache/jobs/423624226>

```
The command "make ${TEST:-test}" exited with 0.

Done. Your build exited with 0.
```

The MinGW target has known failures.

**Comment by peterbud** [comment]
Appveyor is free AFAIK, just like Travis. Or maybe I have missed something?

**Comment by afbjorklund** [comment]
I think we will probably need both, of cross-compile and native. But I didn't mean the cost, I just meant in terms of maintenance, but it seems like we have had lots of various Travis issues lately (this year)...

**Comment by peterbud** [comment]
Ah, OK. For MSYS2 and MINGW64/MINGW32 I had positive experience with Appveyor so far. Wine in Travis however is having more limitations for a Windows CI.

**Comment by afbjorklund** [comment]
Closing this, use Appveyor for Windows (as suggested).

**Pull request closed without merging**
