### PR TITLE
docs: Add scheme to link to fonts.googleapis.com

### PR DESCRIPTION
**Pull request by orgads**

### CODE REVIEW

**Comment by jrosdahl** [comment]
The scheme is not missing – it's a [protocol-relative URL](https://en.wikipedia.org/wiki/URL#prurl). Did you experience some problem with it?

**Comment by orgads** [comment]
Yes. When opening locally, the protocol is `file://`, and obviously this path is not found...

**Comment by jrosdahl** [comment]
OK, then I'll treat it as an improvement instead of a bug which I first thought it was. :slightly_smiling_face:

**Comment by jrosdahl** [comment]
Thanks.

**Pull request merged**
