### PR TITLE
Collect forward declarations in one file

### PR DESCRIPTION
**Pull request by totph**
Plus update copyright information of edited files and
finally fix formatting of CacheEntryWriter.cpp.

### CODE REVIEW

**Comment by jrosdahl** [comment]
> Collect forward declarations in one file

I'm missing why you think that it would be a good idea. To me the current approach is superior; my instinct is to strive to not lump unrelated things together.

> finally fix formatting of CacheEntryWriter.cpp.

That formatting is due to a known bug in clang-format. It's unfortunate but the fix will disappear next time somebody runs `make format`, or (like I do) edit the code with automatic code formatting turned on, so we'll just have to live with it. Or, if you think that it's extremely annoying, add `// clang-format off/on` comments, but I don't think we should bother.

**Comment by totph** [comment]
> > Collect forward declarations in one file
> 
> I'm missing why you think that it would be a good idea. To me the current
> approach is superior; my instinct is to strive to not lump unrelated things together.

These things are indeed unrelated, but then most header files would only contain a single forward include instead of having several copies of the same forward declarations in various files. So, fewer lines and duplications, but one "mudball" file. A matter of taste, certainly.

> bug in clang-format.

Ah, that was it, 7 is the last version with the bug, my mistake. I updated and the issue went away.

**Comment by AlexanderLanin** [comment]
Hi, why are there even forward declarations? Currently I see you have 3, one of which would be removed by followup of #518.

The reason I'm doubtful about forward declaration is that I've heard several people talk about potential overuse: The point being the cpp files that include the header in question need the definition anyway: the implementer needs to work on it and the caller needs to provide it. Exceptions are potentially rare. Forward declarations are especially useful when you headers are so huge, that you don't need most of it in most of the cpp files - however this has been resolved in parallel.

**Comment by totph** [comment]
Forward declarations are required for two mutually dependent files (which was the reason for this commit, it was unintentional and might be better now with the "split ccache.hpp" commit). But they are also a way to cut down on compile times by reducing the number of required includes in header files by only using pointers or references instead of the value type. This project might be small and still compile quickly, but everything counts!

**Comment by jrosdahl** [comment]
@totph: Are you fine with me passing on this one?

**Comment by totph** [comment]
Sure, it's a purely cosmetic change.

**Pull request closed without merging**
