### PR TITLE
MSVC Features

### PR DESCRIPTION
**Pull request by orgads**
This is a rebased version of #952.

Hope I got it right.

### CODE REVIEW

**Comment by cristianadam** [comment]
My commit should already be merged. I don't know why it's being referenced. See https://github.com/ccache/ccache/pull/506

**Comment by orgads** [comment]
> My commit should already be merged. I don't know why it's being referenced. See #506

It looks like there are some changes here (additional flags supported with / and not only -). Maybe this was a preliminary revision of your commit? Should I omit this commit?

**Comment by cristianadam** [comment]
> > My commit should already be merged. I don't know why it's being referenced. See #506
> 
> It looks like there are some changes here (additional flags supported with `/` and not only `-`). Maybe this was a preliminary revision of your commit? Should I omit this commit?

It creates a bit of confusion. But having both `/` and `-` is a good thing. The commit should have a different commit message.

**Comment by orgads** [comment]
Done

**Comment by cristianadam** [comment]
With this PR we can then update the page at https://ccache.dev/platform-compiler-language-support.html.

- cl is supported
- clang-cl is also supported

**Comment by jrosdahl** [comment]
Thanks for driving the MSVC features forward.

However, as mentioned in https://github.com/ccache/ccache/pull/952#issuecomment-1009285845, I would prefer not to review and merge the features in a single PR.

> Also note It looks like there are some changes here (additional flags supported with / and not only -)

The special handling of `/` version of the options is obsolete as of #954.

**Comment by orgads** [comment]
Regarding the `/`, I thought so, but didn't know where to look. Thanks for the reference :)

I'll split the other commits.

**Pull request closed without merging**
