### PR TITLE
Install the cuda deb repository manually

### PR DESCRIPTION
**Pull request by afbjorklund**
Try to see why it times out in Travis

Issue #287

### CODE REVIEW

**Comment by afbjorklund** [comment]
https://travis-ci.org/ccache/ccache/jobs/407598234

**Comment by afbjorklund** [comment]
https://travis-ci.org/ccache/ccache/jobs/407602714

**Comment by afbjorklund** [comment]
https://travis-ci.org/ccache/ccache/jobs/407615130

**Comment by afbjorklund** [comment]
https://travis-ci.org/ccache/ccache/jobs/407625487

**Comment by jrosdahl** [comment]
Is this something you want applied or is it only to debug travis by pushing to the pull request branch?

**Comment by afbjorklund** [comment]
It **was** a workaround (#287), for when Travis wasn't working. But seems to be unneeded, for now...
It's more like Travis has interim networking issue, then it being something fundamentally wrong with it ?

**Pull request closed without merging**
