### PR TITLE
Add aggregated file storing all the results

### PR DESCRIPTION
**Pull request by afbjorklund**
From #218

### CODE REVIEW

**Comment by jrosdahl** [comment]
Regarding the "work in progress" label: Are you aware of the [draft pull requests](https://github.blog/2019-02-14-introducing-draft-pull-requests/) feature?

**Comment by jrosdahl** [comment]
What's the status of this pull request? I understand that it's not ready for merging, but do you want me to review/comment on it in its current state?

**Comment by afbjorklund** [comment]
> Regarding the "work in progress" label: Are you aware of the [draft pull requests](https://github.blog/2019-02-14-introducing-draft-pull-requests/) feature?

Nope, I just copied what was used in other projects (that have a merge bot running)

**Comment by jrosdahl** [comment]
> It just seemed more reasonable to have it here as a PR, instead of a private branch or code snippets.

I'm still unsure about the status of this pull request since you didn't quite answer that question... Do you want me to review/comment on it in its current state, or do you want me to continue working on the code?

**Comment by afbjorklund** [comment]
It is missing a buffer for the file copy, and I need to change the name of some functions/variables still...

- [ ] version field
- [ ] copy buffer
- [ ] rename things
- [ ] update tests

Feel free to review, but it is not yet complete. There's going to be a _lot_ of impact on the tests, later on.

**Comment by jrosdahl** [comment]
Got it, thanks.

**Comment by afbjorklund** [comment]
Updated the above, but there's some kind of crash (segfault) when handling the .stderr

**Comment by afbjorklund** [comment]
Should be safe to merge, now that it is not the default (i.e. the feature is not enabled).

You will need to `./configure --enable-aggregated` to be able to work on it, though.

https://en.wikipedia.org/wiki/Feature_toggle

**Comment by afbjorklund** [comment]
> Updated the above, but there's some kind of crash (segfault) when handling the .stderr

Fixed the crash, was due to stray free and get after rewriting. Also file handling was wrong.

**Comment by afbjorklund** [comment]
Now the tests have been updated as well, mostly it was about number of files in cache.

**Comment by jrosdahl** [comment]
Thanks! I hope to find time to look at this soon.

**Comment by jrosdahl** [comment]
Merged to dev/aggregation temporarily. I will work to get this to master in the near term.

Thanks!

**Pull request merged**
