### PR TITLE
Add LGTM code quality badges

### PR DESCRIPTION
**Pull request by xcorail**
Hi there!

I thought you might be interested in adding these [LGTM code quality badges](https://lgtm.com/projects/g/ccache/ccache/ci/#badges) to your project, to show how you care about code quality and encourage contributors to do the same.
To get an idea of the analyses reflected by these grades, check the [alerts discovered by LGTM](https://lgtm.com/projects/g/ccache/ccache).

N.B.: I am on the team behind LGTM.com, I'd appreciate your feedback on this initiative, whether you're interested or not, if you find time to drop me a line. Thanks.

### CODE REVIEW

**Comment by afbjorklund** [comment]
Interesting, there are some "alerts" (4) shown at the moment:
https://lgtm.com/projects/g/ccache/ccache/alerts?mode=list

Should probably be investigated, see if they are real or false.
We got a grade of just "B", whereas the python hacks are "A+"

https://semmle.com/lgtm

Wouldn't hurt, I suppose ?

**Comment by afbjorklund** [comment]
Alert summary: 0 errors, 2 warnings, 2 recommendations

So nothing critical, but always good to be back to "zero" ?
But the tool is probably right about the naming of globals...

And we did have a real such bug, in the `dev/memcached`

**Comment by jrosdahl** [comment]
OK, let's try them out. Applied on master.

**Comment by xcorail** [comment]
Hi @afbjorklund @jrosdahl 

Happy you found it useful.
A few precisions : 
* This service is 100% free for open source projects
* Our queries are open source at https://github.com/Semmle/ql
* Our recommended usage is to integrate LGTM with your Pull Requests. PRs will be analyzed immediately and LGTM will report any new problem (or fix) directly in the PR. This is a [one-click operation](https://lgtm.com/projects/g/ccache/ccache/ci/). Otherwise, LGTM will poll your repo once a day and analyze all new commits, most recent first
* Suggestions and feedback are welcome: https://discuss.lgtm.com/

Thanks, and good luck to the ccache team (I was a happy user of ccache in my previous job ;-) )

**Comment by afbjorklund** [comment]
@xcorail : thanks for a friendly invitation, and encouraging to improve our code.

I _think_ we will settle for the current [Travis integration](https://travis-ci.org/ccache/ccache) (also available offline), for now...

**Pull request closed without merging**
