### PR TITLE
Add optional deduplication mode

### PR DESCRIPTION
**Pull request by afbjorklund**
This is a simple version of the deduplication mode, without making it mandatory...

It stores a "binary" hash with a link to the original hash, similar to the manifest file.

Then it can store a "reference" (.ref) to this binary, instead of storing another copy.

Another feature that adds runtime overhead (time), in favor of disk usage (space).

Implements #98

### CODE REVIEW

**Comment by afbjorklund** [comment]
Currently the .binary file just contains the hash prefix of all the other files, not actually the data (as in #218)

**Comment by jrosdahl** [comment]
Looks like a good implementation at a first glance, thanks! However, I would like to postpone this to after #218. Does that sound reasonable?

**Comment by afbjorklund** [comment]
Perfectly reasonable, as I'm not fully sure trading speed for size is a good deal.

**Comment by afbjorklund** [comment]
With the current implementation of the aggregated files, this idea would still work as-is.

i.e. you would still get the key, just use it to refer to 1 aggregated file instead of 7 single

**Comment by jrosdahl** [comment]
> With the current implementation of the aggregated files, this idea would still work as-is.
> i.e. you would still get the key, just use it to refer to 1 aggregated file instead of 7 single

My suggestion to wait with this was due to implementation dependencies, not that the idea wouldn't fly.

**Comment by afbjorklund** [comment]
Closed, due to result files.

**Pull request closed without merging**
