### PR TITLE
Fix DIR_DELIM_CH for win32 and non-win32 platforms, values were mixed up

### PR DESCRIPTION
**Pull request by oded-ist**

### CODE REVIEW

**Comment by afbjorklund** [comment]
LGTM

**Comment by jd-gascuel** [comment]
I agree to !

**Comment by afbjorklund** [comment]
I suppose it mostly shows the lack of the tests on the Windows platform... (#119)

**Comment by jrosdahl** [comment]
> I suppose it mostly shows the lack of the tests on the Windows platform...

In this case, I'm to blame both for the mixup and for not writing a test case... Fixed in c5effc8a.

**Comment by jrosdahl** [comment]
Thanks! Applied to 3.3-maint.

**Pull request closed without merging**
