### PR TITLE
Allow ccache to work with distcc's "pump" wrapper

### PR DESCRIPTION
**Pull request by afbjorklund**
The recommended way to use distcc is to start the include_server.py just once, but make it work with the `distcc-pump` wrapper too... It outputs some noise to standard output, that needs to be filtered out.

```
For example:
      eval `pump --startup`
      make -j80
      pump --shutdown
```

In order for the local machine to not get overrun by all the preprocessing, it is important to set `CCACHE_PREFIX_CPP=distcc` and patch bugs about setting --localslots_cpp (distcc/distcc#161).

### CODE REVIEW

**Comment by afbjorklund** [comment]
Would fix issues reported in #142, by not writing to stdout anymore.

**Comment by jrosdahl** [comment]
Looks good, although it's an unfortunate hack.

I think that pump should print such progress messages to `UNCACHED_ERR_FD` just like distcc does.

**Comment by afbjorklund** [comment]
Yeah, fixing it in distcc would probably be the better option - but it is hard to do retroactively (a lot of broken `distcc-pump` out there), and there's not much development/maintenance ongoing in distcc (sadly).

Here is the culprit: https://github.com/distcc/distcc/blob/master/pump.in

**Comment by afbjorklund** [comment]
Note that using pump mode is now *required*, when using the cpp2 option (not using the preprocessor).

**Comment by jrosdahl** [comment]
Applied on master, thanks!

**Pull request closed without merging**
